sudo: false

language: node_js
node_js: "12.16.2"

cache:
  directories:
#    - node_modules
#    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
#    - $HOME/.npm/_prebuilds

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - USE_HARD_LINKS=false

jobs:
  include:
    #- stage: Test
    #  script:
    #    - yarn test-all
    - stage: Deploy Linux
      if: tag IS present
      os: linux
      dist: trusty
      script:
        - yarn package-ci -- --linux -p always
    - stage: Deploy Mac and Windows
      if: tag IS present
      os: osx
      osx_image: xcode10.1
      script:
        - yarn package-ci -- --mac -p always
        - yarn package-ci -- --win -p always
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
