// flow-typed signature: be7a43008adce24e025895476b91f103
// flow-typed version: <<STUB>>/chalk_v^3.0.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chalk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chalk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chalk/source' {
  declare module.exports: any;
}

declare module 'chalk/source/templates' {
  declare module.exports: any;
}

declare module 'chalk/source/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chalk/source/index' {
  declare module.exports: $Exports<'chalk/source'>;
}
declare module 'chalk/source/index.js' {
  declare module.exports: $Exports<'chalk/source'>;
}
declare module 'chalk/source/templates.js' {
  declare module.exports: $Exports<'chalk/source/templates'>;
}
declare module 'chalk/source/util.js' {
  declare module.exports: $Exports<'chalk/source/util'>;
}
