// flow-typed signature: d42232f0161277cc6ea50b328dcada44
// flow-typed version: <<STUB>>/dat-sdk_v^2.0.0-3/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dat-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dat-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dat-sdk/auto' {
  declare module.exports: any;
}

declare module 'dat-sdk/dns-web' {
  declare module.exports: any;
}

declare module 'dat-sdk/example/example' {
  declare module.exports: any;
}

declare module 'dat-sdk/localstorage-web' {
  declare module.exports: any;
}

declare module 'dat-sdk/localstorage' {
  declare module.exports: any;
}

declare module 'dat-sdk/test-promise' {
  declare module.exports: any;
}

declare module 'dat-sdk/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dat-sdk/auto.js' {
  declare module.exports: $Exports<'dat-sdk/auto'>;
}
declare module 'dat-sdk/dns-web.js' {
  declare module.exports: $Exports<'dat-sdk/dns-web'>;
}
declare module 'dat-sdk/example/example.js' {
  declare module.exports: $Exports<'dat-sdk/example/example'>;
}
declare module 'dat-sdk/index' {
  declare module.exports: $Exports<'dat-sdk'>;
}
declare module 'dat-sdk/index.js' {
  declare module.exports: $Exports<'dat-sdk'>;
}
declare module 'dat-sdk/localstorage-web.js' {
  declare module.exports: $Exports<'dat-sdk/localstorage-web'>;
}
declare module 'dat-sdk/localstorage.js' {
  declare module.exports: $Exports<'dat-sdk/localstorage'>;
}
declare module 'dat-sdk/test-promise.js' {
  declare module.exports: $Exports<'dat-sdk/test-promise'>;
}
declare module 'dat-sdk/test.js' {
  declare module.exports: $Exports<'dat-sdk/test'>;
}
