// flow-typed signature: 838b5300778d78f7d3abbb968ac16a9d
// flow-typed version: <<STUB>>/env-path_v^1.0.7/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'env-path'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'env-path' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'env-path/lib/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'env-path/lib/main.js' {
  declare module.exports: $Exports<'env-path/lib/main'>;
}
