// flow-typed signature: 2b034ed48c8f27d9ce01cfa361b73f8d
// flow-typed version: <<STUB>>/levelup_v^4.3.2/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'levelup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'levelup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'levelup/lib/batch' {
  declare module.exports: any;
}

declare module 'levelup/lib/common' {
  declare module.exports: any;
}

declare module 'levelup/lib/levelup' {
  declare module.exports: any;
}

declare module 'levelup/lib/promisify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'levelup/lib/batch.js' {
  declare module.exports: $Exports<'levelup/lib/batch'>;
}
declare module 'levelup/lib/common.js' {
  declare module.exports: $Exports<'levelup/lib/common'>;
}
declare module 'levelup/lib/levelup.js' {
  declare module.exports: $Exports<'levelup/lib/levelup'>;
}
declare module 'levelup/lib/promisify.js' {
  declare module.exports: $Exports<'levelup/lib/promisify'>;
}
