// flow-typed signature: 692696c49d1630703a0d996f979d319c
// flow-typed version: <<STUB>>/memdown_v^5.1.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'memdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'memdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'memdown/immediate-browser' {
  declare module.exports: any;
}

declare module 'memdown/immediate' {
  declare module.exports: any;
}

declare module 'memdown/memdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'memdown/immediate-browser.js' {
  declare module.exports: $Exports<'memdown/immediate-browser'>;
}
declare module 'memdown/immediate.js' {
  declare module.exports: $Exports<'memdown/immediate'>;
}
declare module 'memdown/memdown.js' {
  declare module.exports: $Exports<'memdown/memdown'>;
}
