// flow-typed signature: bf559e219e53e728db12e9c6f38227ab
// flow-typed version: <<STUB>>/random-access-memory_v^3.1.1/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'random-access-memory'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'random-access-memory' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'random-access-memory/example' {
  declare module.exports: any;
}

declare module 'random-access-memory/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'random-access-memory/example.js' {
  declare module.exports: $Exports<'random-access-memory/example'>;
}
declare module 'random-access-memory/index' {
  declare module.exports: $Exports<'random-access-memory'>;
}
declare module 'random-access-memory/index.js' {
  declare module.exports: $Exports<'random-access-memory'>;
}
declare module 'random-access-memory/test.js' {
  declare module.exports: $Exports<'random-access-memory/test'>;
}
