// flow-typed signature: 84a8ee01967b2f4ed72c33db36098c4d
// flow-typed version: <<STUB>>/@sindresorhus/slugify_v^0.11.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sindresorhus/slugify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sindresorhus/slugify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sindresorhus/slugify/overridable-replacements' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sindresorhus/slugify/index' {
  declare module.exports: $Exports<'@sindresorhus/slugify'>;
}
declare module '@sindresorhus/slugify/index.js' {
  declare module.exports: $Exports<'@sindresorhus/slugify'>;
}
declare module '@sindresorhus/slugify/overridable-replacements.js' {
  declare module.exports: $Exports<'@sindresorhus/slugify/overridable-replacements'>;
}
